// This file is auto-generated by @hey-api/openapi-ts

export const ApplicationAuditEventPublicSchema = {
    properties: {
        action: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Action'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Event Metadata'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        actor_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor User Id'
        },
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        }
    },
    type: 'object',
    required: ['action', 'id', 'event_metadata', 'application_id'],
    title: 'ApplicationAuditEventPublic'
} as const;

export const ApplicationAuditTrailPublicSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        events: {
            items: {
                '$ref': '#/components/schemas/ApplicationAuditEventPublic'
            },
            type: 'array',
            title: 'Events'
        }
    },
    type: 'object',
    required: ['application_id', 'events'],
    title: 'ApplicationAuditTrailPublic'
} as const;

export const ApplicationCaseExplanationPublicSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        summary: {
            type: 'string',
            maxLength: 3000,
            minLength: 1,
            title: 'Summary'
        },
        recommended_action: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Recommended Action'
        },
        key_risks: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Risks'
        },
        missing_evidence: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Missing Evidence'
        },
        next_steps: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Next Steps'
        },
        generated_by: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Generated By'
        },
        generated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['application_id', 'summary', 'recommended_action', 'key_risks', 'missing_evidence', 'next_steps', 'generated_by'],
    title: 'ApplicationCaseExplanationPublic'
} as const;

export const ApplicationDecisionBreakdownPublicSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        recommendation: {
            type: 'string',
            title: 'Recommendation'
        },
        confidence_score: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Confidence Score'
        },
        risk_level: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: 'Risk Level'
        },
        rules: {
            items: {
                '$ref': '#/components/schemas/EligibilityRuleResultPublic'
            },
            type: 'array',
            title: 'Rules'
        }
    },
    type: 'object',
    required: ['application_id', 'recommendation', 'confidence_score', 'risk_level', 'rules'],
    title: 'ApplicationDecisionBreakdownPublic'
} as const;

export const ApplicationDocumentPublicSchema = {
    properties: {
        document_type: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Document Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        file_size_bytes: {
            type: 'integer',
            title: 'File Size Bytes'
        },
        status: {
            '$ref': '#/components/schemas/DocumentStatus'
        },
        ocr_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ocr Text'
        },
        extracted_fields: {
            additionalProperties: true,
            type: 'object',
            title: 'Extracted Fields'
        },
        processing_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Error'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        }
    },
    type: 'object',
    required: ['document_type', 'id', 'original_filename', 'mime_type', 'file_size_bytes', 'status', 'extracted_fields', 'application_id'],
    title: 'ApplicationDocumentPublic'
} as const;

export const ApplicationDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApplicationDocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApplicationDocumentsPublic'
} as const;

export const ApplicationEvidenceRecommendationPublicSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        recommended_document_types: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Recommended Document Types'
        },
        rationale_by_document_type: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Rationale By Document Type'
        },
        recommended_next_actions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Recommended Next Actions'
        },
        generated_by: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Generated By'
        },
        generated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['application_id', 'recommended_document_types', 'rationale_by_document_type', 'recommended_next_actions', 'generated_by'],
    title: 'ApplicationEvidenceRecommendationPublic'
} as const;

export const ApplicationProcessRequestSchema = {
    properties: {
        force_reprocess: {
            type: 'boolean',
            title: 'Force Reprocess',
            default: false
        }
    },
    type: 'object',
    title: 'ApplicationProcessRequest'
} as const;

export const ApplicationStatusSchema = {
    type: 'string',
    enum: ['draft', 'documents_uploaded', 'queued', 'processing', 'review_ready', 'approved', 'rejected', 'more_info_required'],
    title: 'ApplicationStatus'
} as const;

export const Body_applications_upload_application_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        document_type: {
            type: 'string',
            title: 'Document Type'
        }
    },
    type: 'object',
    required: ['file', 'document_type'],
    title: 'Body_applications-upload_application_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CitizenshipApplicationCreateSchema = {
    properties: {
        applicant_full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Applicant Full Name'
        },
        applicant_nationality: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Applicant Nationality'
        },
        applicant_birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Applicant Birth Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['applicant_full_name', 'applicant_nationality'],
    title: 'CitizenshipApplicationCreate'
} as const;

export const CitizenshipApplicationPublicSchema = {
    properties: {
        applicant_full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Applicant Full Name'
        },
        applicant_nationality: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Applicant Nationality'
        },
        applicant_birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Applicant Birth Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/ApplicationStatus'
        },
        recommendation_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Summary'
        },
        confidence_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confidence Score'
        },
        priority_score: {
            type: 'number',
            title: 'Priority Score',
            default: 0
        },
        sla_due_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sla Due At'
        },
        final_decision: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Decision'
        },
        final_decision_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Decision Reason'
        },
        final_decision_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Decision At'
        },
        final_decision_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Decision By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['applicant_full_name', 'applicant_nationality', 'id', 'status', 'owner_id'],
    title: 'CitizenshipApplicationPublic'
} as const;

export const CitizenshipApplicationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CitizenshipApplicationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CitizenshipApplicationsPublic'
} as const;

export const DocumentStatusSchema = {
    type: 'string',
    enum: ['uploaded', 'processing', 'processed', 'failed'],
    title: 'DocumentStatus'
} as const;

export const EligibilityRuleResultPublicSchema = {
    properties: {
        rule_code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Rule Code'
        },
        rule_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Rule Name'
        },
        passed: {
            type: 'boolean',
            title: 'Passed'
        },
        score: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Score'
        },
        weight: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Weight'
        },
        rationale: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Rationale'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        evidence: {
            additionalProperties: true,
            type: 'object',
            title: 'Evidence'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        }
    },
    type: 'object',
    required: ['rule_code', 'rule_name', 'passed', 'score', 'weight', 'rationale', 'id', 'evidence', 'application_id'],
    title: 'EligibilityRuleResultPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReviewDecisionActionSchema = {
    type: 'string',
    enum: ['approve', 'reject', 'request_more_info'],
    title: 'ReviewDecisionAction'
} as const;

export const ReviewDecisionRequestSchema = {
    properties: {
        action: {
            '$ref': '#/components/schemas/ReviewDecisionAction'
        },
        reason: {
            type: 'string',
            maxLength: 1000,
            minLength: 8,
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['action', 'reason'],
    title: 'ReviewDecisionRequest'
} as const;

export const ReviewQueueItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        applicant_full_name: {
            type: 'string',
            title: 'Applicant Full Name'
        },
        applicant_nationality: {
            type: 'string',
            title: 'Applicant Nationality'
        },
        status: {
            '$ref': '#/components/schemas/ApplicationStatus'
        },
        recommendation_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Summary'
        },
        confidence_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confidence Score'
        },
        risk_level: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: 'Risk Level'
        },
        priority_score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Priority Score'
        },
        sla_due_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sla Due At'
        },
        is_overdue: {
            type: 'boolean',
            title: 'Is Overdue'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'applicant_full_name', 'applicant_nationality', 'status', 'risk_level', 'priority_score', 'is_overdue'],
    title: 'ReviewQueueItemPublic'
} as const;

export const ReviewQueueMetricsPublicSchema = {
    properties: {
        pending_manual_count: {
            type: 'integer',
            title: 'Pending Manual Count'
        },
        overdue_count: {
            type: 'integer',
            title: 'Overdue Count'
        },
        high_priority_count: {
            type: 'integer',
            title: 'High Priority Count'
        },
        avg_waiting_days: {
            type: 'number',
            title: 'Avg Waiting Days'
        },
        daily_manual_capacity: {
            type: 'integer',
            title: 'Daily Manual Capacity'
        },
        estimated_days_to_clear_backlog: {
            type: 'number',
            title: 'Estimated Days To Clear Backlog'
        }
    },
    type: 'object',
    required: ['pending_manual_count', 'overdue_count', 'high_priority_count', 'avg_waiting_days', 'daily_manual_capacity', 'estimated_days_to_clear_backlog'],
    title: 'ReviewQueueMetricsPublic'
} as const;

export const ReviewQueuePublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReviewQueueItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReviewQueuePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;