// This file is auto-generated by @hey-api/openapi-ts

export type ApplicationAuditEventPublic = {
    action: string;
    reason?: (string | null);
    id: string;
    event_metadata: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
    actor_user_id?: (string | null);
    application_id: string;
};

export type ApplicationAuditTrailPublic = {
    application_id: string;
    events: Array<ApplicationAuditEventPublic>;
};

export type ApplicationCaseExplanationPublic = {
    application_id: string;
    summary: string;
    recommended_action: string;
    key_risks: Array<(string)>;
    missing_evidence: Array<(string)>;
    next_steps: Array<(string)>;
    generated_by: string;
    generated_at?: (string | null);
};

export type ApplicationDecisionBreakdownPublic = {
    application_id: string;
    recommendation: string;
    confidence_score: number;
    risk_level: string;
    rules: Array<EligibilityRuleResultPublic>;
};

export type ApplicationDocumentPublic = {
    document_type: string;
    id: string;
    original_filename: string;
    mime_type: string;
    file_size_bytes: number;
    status: DocumentStatus;
    ocr_text?: (string | null);
    extracted_fields: {
        [key: string]: unknown;
    };
    processing_error?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    application_id: string;
};

export type ApplicationDocumentsPublic = {
    data: Array<ApplicationDocumentPublic>;
    count: number;
};

export type ApplicationEvidenceRecommendationPublic = {
    application_id: string;
    recommended_document_types: Array<(string)>;
    rationale_by_document_type: {
        [key: string]: (string);
    };
    recommended_next_actions: Array<(string)>;
    generated_by: string;
    generated_at?: (string | null);
};

export type ApplicationProcessRequest = {
    force_reprocess?: boolean;
};

export type ApplicationStatus = 'draft' | 'documents_uploaded' | 'queued' | 'processing' | 'review_ready' | 'approved' | 'rejected' | 'more_info_required';

export type Body_applications_upload_application_document = {
    file: (Blob | File);
    document_type: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CitizenshipApplicationCreate = {
    applicant_full_name: string;
    applicant_nationality: string;
    applicant_birth_date?: (string | null);
    notes?: (string | null);
};

export type CitizenshipApplicationPublic = {
    applicant_full_name: string;
    applicant_nationality: string;
    applicant_birth_date?: (string | null);
    notes?: (string | null);
    id: string;
    status: ApplicationStatus;
    recommendation_summary?: (string | null);
    confidence_score?: (number | null);
    priority_score?: number;
    sla_due_at?: (string | null);
    final_decision?: (string | null);
    final_decision_reason?: (string | null);
    final_decision_at?: (string | null);
    final_decision_by_id?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    owner_id: string;
};

export type CitizenshipApplicationsPublic = {
    data: Array<CitizenshipApplicationPublic>;
    count: number;
};

export type DocumentStatus = 'uploaded' | 'processing' | 'processed' | 'failed';

export type EligibilityRuleResultPublic = {
    rule_code: string;
    rule_name: string;
    passed: boolean;
    score: number;
    weight: number;
    rationale: string;
    id: string;
    evidence: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
    application_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReviewDecisionAction = 'approve' | 'reject' | 'request_more_info';

export type ReviewDecisionRequest = {
    action: ReviewDecisionAction;
    reason: string;
};

export type ReviewQueueItemPublic = {
    id: string;
    applicant_full_name: string;
    applicant_nationality: string;
    status: ApplicationStatus;
    recommendation_summary?: (string | null);
    confidence_score?: (number | null);
    risk_level: string;
    priority_score: number;
    sla_due_at?: (string | null);
    is_overdue: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ReviewQueueMetricsPublic = {
    pending_manual_count: number;
    overdue_count: number;
    high_priority_count: number;
    avg_waiting_days: number;
    daily_manual_capacity: number;
    estimated_days_to_clear_backlog: number;
};

export type ReviewQueuePublic = {
    data: Array<ReviewQueueItemPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ApplicationsCreateApplicationData = {
    requestBody: CitizenshipApplicationCreate;
};

export type ApplicationsCreateApplicationResponse = (CitizenshipApplicationPublic);

export type ApplicationsReadApplicationsData = {
    limit?: number;
    skip?: number;
};

export type ApplicationsReadApplicationsResponse = (CitizenshipApplicationsPublic);

export type ApplicationsReadReviewQueueData = {
    limit?: number;
    skip?: number;
};

export type ApplicationsReadReviewQueueResponse = (ReviewQueuePublic);

export type ApplicationsReadReviewQueueMetricsData = {
    dailyManualCapacity?: number;
};

export type ApplicationsReadReviewQueueMetricsResponse = (ReviewQueueMetricsPublic);

export type ApplicationsReadApplicationData = {
    applicationId: string;
};

export type ApplicationsReadApplicationResponse = (CitizenshipApplicationPublic);

export type ApplicationsUploadApplicationDocumentData = {
    applicationId: string;
    formData: Body_applications_upload_application_document;
};

export type ApplicationsUploadApplicationDocumentResponse = (ApplicationDocumentPublic);

export type ApplicationsReadApplicationDocumentsData = {
    applicationId: string;
};

export type ApplicationsReadApplicationDocumentsResponse = (ApplicationDocumentsPublic);

export type ApplicationsQueueApplicationProcessingData = {
    applicationId: string;
    requestBody: ApplicationProcessRequest;
};

export type ApplicationsQueueApplicationProcessingResponse = (CitizenshipApplicationPublic);

export type ApplicationsReadApplicationDecisionBreakdownData = {
    applicationId: string;
};

export type ApplicationsReadApplicationDecisionBreakdownResponse = (ApplicationDecisionBreakdownPublic);

export type ApplicationsReadApplicationCaseExplainerData = {
    applicationId: string;
};

export type ApplicationsReadApplicationCaseExplainerResponse = (ApplicationCaseExplanationPublic);

export type ApplicationsReadApplicationEvidenceRecommendationsData = {
    applicationId: string;
};

export type ApplicationsReadApplicationEvidenceRecommendationsResponse = (ApplicationEvidenceRecommendationPublic);

export type ApplicationsSubmitReviewDecisionData = {
    applicationId: string;
    requestBody: ReviewDecisionRequest;
};

export type ApplicationsSubmitReviewDecisionResponse = (CitizenshipApplicationPublic);

export type ApplicationsReadApplicationAuditTrailData = {
    applicationId: string;
};

export type ApplicationsReadApplicationAuditTrailResponse = (ApplicationAuditTrailPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);