name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: List exact steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Run ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, backend/frontend versions, and relevant logs

  - type: textarea
    id: extra
    attributes:
      label: Additional context
